/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.firebaseapphosting.v1beta.model;

/**
 * Represents a single FAH supported runtime. Although instances of this resource are parented by a
 * project and location, the set of available runtimes may vary across projects and locations, for
 * example, during staged rollouts of new runtime support.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Firebase App Hosting API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SupportedRuntime extends com.google.api.client.json.GenericJson {

  /**
   * Output only. True if Automatic Base Image Updates (ABIU) is supported for this runtime.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean automaticBaseImageUpdatesSupported;

  /**
   * Output only. The time at which this runtime will be decommissioned. After this date, the
   * runtime can no longer be used for new builds.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String decommissionTime;

  /**
   * Output only. The time at which this runtime will effectively be deprecated. After this date,
   * the runtime is still usable but may not receive new features or updates.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String deprecateTime;

  /**
   * Identifier. The resource name of the supported runtime. Format:
   * projects/{project}/locations/{location}/supportedRuntimes/{runtime_id}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Output only. The identifier of the runtime, e.g., "nodejs22".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String runtimeId;

  /**
   * Output only. True if Automatic Base Image Updates (ABIU) is supported for this runtime.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAutomaticBaseImageUpdatesSupported() {
    return automaticBaseImageUpdatesSupported;
  }

  /**
   * Output only. True if Automatic Base Image Updates (ABIU) is supported for this runtime.
   * @param automaticBaseImageUpdatesSupported automaticBaseImageUpdatesSupported or {@code null} for none
   */
  public SupportedRuntime setAutomaticBaseImageUpdatesSupported(java.lang.Boolean automaticBaseImageUpdatesSupported) {
    this.automaticBaseImageUpdatesSupported = automaticBaseImageUpdatesSupported;
    return this;
  }

  /**
   * Output only. The time at which this runtime will be decommissioned. After this date, the
   * runtime can no longer be used for new builds.
   * @return value or {@code null} for none
   */
  public String getDecommissionTime() {
    return decommissionTime;
  }

  /**
   * Output only. The time at which this runtime will be decommissioned. After this date, the
   * runtime can no longer be used for new builds.
   * @param decommissionTime decommissionTime or {@code null} for none
   */
  public SupportedRuntime setDecommissionTime(String decommissionTime) {
    this.decommissionTime = decommissionTime;
    return this;
  }

  /**
   * Output only. The time at which this runtime will effectively be deprecated. After this date,
   * the runtime is still usable but may not receive new features or updates.
   * @return value or {@code null} for none
   */
  public String getDeprecateTime() {
    return deprecateTime;
  }

  /**
   * Output only. The time at which this runtime will effectively be deprecated. After this date,
   * the runtime is still usable but may not receive new features or updates.
   * @param deprecateTime deprecateTime or {@code null} for none
   */
  public SupportedRuntime setDeprecateTime(String deprecateTime) {
    this.deprecateTime = deprecateTime;
    return this;
  }

  /**
   * Identifier. The resource name of the supported runtime. Format:
   * projects/{project}/locations/{location}/supportedRuntimes/{runtime_id}
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Identifier. The resource name of the supported runtime. Format:
   * projects/{project}/locations/{location}/supportedRuntimes/{runtime_id}
   * @param name name or {@code null} for none
   */
  public SupportedRuntime setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Output only. The identifier of the runtime, e.g., "nodejs22".
   * @return value or {@code null} for none
   */
  public java.lang.String getRuntimeId() {
    return runtimeId;
  }

  /**
   * Output only. The identifier of the runtime, e.g., "nodejs22".
   * @param runtimeId runtimeId or {@code null} for none
   */
  public SupportedRuntime setRuntimeId(java.lang.String runtimeId) {
    this.runtimeId = runtimeId;
    return this;
  }

  @Override
  public SupportedRuntime set(String fieldName, Object value) {
    return (SupportedRuntime) super.set(fieldName, value);
  }

  @Override
  public SupportedRuntime clone() {
    return (SupportedRuntime) super.clone();
  }

}
