/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.aiplatform.v1beta1.model;

/**
 * The spec for a pre-defined metric.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Agent Platform API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudAiplatformV1beta1PredefinedMetricSpec extends com.google.api.client.json.GenericJson {

  /**
   * Required. The name of a pre-defined metric, such as "instruction_following_v1" or
   * "text_quality_v1".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String metricSpecName;

  /**
   * Optional. The parameters needed to run the pre-defined metric.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.lang.Object> metricSpecParameters;

  /**
   * Optional. Per-step autorater overrides for this predefined metric. Keys are evaluation stage
   * names (snake_case). Valid keys: "intent_extraction", "rubric_generation", "rubric_validation".
   * Unknown keys return INVALID_ARGUMENT.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, GoogleCloudAiplatformV1beta1AutoraterConfig> stepAutoraterConfigs;

  static {
    // hack to force ProGuard to consider GoogleCloudAiplatformV1beta1AutoraterConfig used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleCloudAiplatformV1beta1AutoraterConfig.class);
  }

  /**
   * Required. The name of a pre-defined metric, such as "instruction_following_v1" or
   * "text_quality_v1".
   * @return value or {@code null} for none
   */
  public java.lang.String getMetricSpecName() {
    return metricSpecName;
  }

  /**
   * Required. The name of a pre-defined metric, such as "instruction_following_v1" or
   * "text_quality_v1".
   * @param metricSpecName metricSpecName or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1PredefinedMetricSpec setMetricSpecName(java.lang.String metricSpecName) {
    this.metricSpecName = metricSpecName;
    return this;
  }

  /**
   * Optional. The parameters needed to run the pre-defined metric.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.lang.Object> getMetricSpecParameters() {
    return metricSpecParameters;
  }

  /**
   * Optional. The parameters needed to run the pre-defined metric.
   * @param metricSpecParameters metricSpecParameters or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1PredefinedMetricSpec setMetricSpecParameters(java.util.Map<String, java.lang.Object> metricSpecParameters) {
    this.metricSpecParameters = metricSpecParameters;
    return this;
  }

  /**
   * Optional. Per-step autorater overrides for this predefined metric. Keys are evaluation stage
   * names (snake_case). Valid keys: "intent_extraction", "rubric_generation", "rubric_validation".
   * Unknown keys return INVALID_ARGUMENT.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, GoogleCloudAiplatformV1beta1AutoraterConfig> getStepAutoraterConfigs() {
    return stepAutoraterConfigs;
  }

  /**
   * Optional. Per-step autorater overrides for this predefined metric. Keys are evaluation stage
   * names (snake_case). Valid keys: "intent_extraction", "rubric_generation", "rubric_validation".
   * Unknown keys return INVALID_ARGUMENT.
   * @param stepAutoraterConfigs stepAutoraterConfigs or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1PredefinedMetricSpec setStepAutoraterConfigs(java.util.Map<String, GoogleCloudAiplatformV1beta1AutoraterConfig> stepAutoraterConfigs) {
    this.stepAutoraterConfigs = stepAutoraterConfigs;
    return this;
  }

  @Override
  public GoogleCloudAiplatformV1beta1PredefinedMetricSpec set(String fieldName, Object value) {
    return (GoogleCloudAiplatformV1beta1PredefinedMetricSpec) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudAiplatformV1beta1PredefinedMetricSpec clone() {
    return (GoogleCloudAiplatformV1beta1PredefinedMetricSpec) super.clone();
  }

}
