/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.aiplatform.v1beta1.model;

/**
 * Selects the model configuration for an agent. Starts with just the model id/alias; extensible
 * with further model parameters without a breaking change.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Agent Platform API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleCloudAiplatformV1beta1AgentModelConfig extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Publisher model resource name (an `aiplatform.googleapis.com/PublisherModel`) of the
   * form "publishers/{publisher}/models/{model}", e.g. "publishers/anthropic/models/claude-
   * opus-4-8" or "publishers/google/models/gemini-3-flash". Empty means the agent's default gemini
   * model.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String model;

  /**
   * Optional. Sampling temperature for the model's generation config (valid range (0.0, 2.0]); a
   * value outside that range leaves the backend default standing.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Float temperature;

  /**
   * Optional. Publisher model resource name (an `aiplatform.googleapis.com/PublisherModel`) of the
   * form "publishers/{publisher}/models/{model}", e.g. "publishers/anthropic/models/claude-
   * opus-4-8" or "publishers/google/models/gemini-3-flash". Empty means the agent's default gemini
   * model.
   * @return value or {@code null} for none
   */
  public java.lang.String getModel() {
    return model;
  }

  /**
   * Optional. Publisher model resource name (an `aiplatform.googleapis.com/PublisherModel`) of the
   * form "publishers/{publisher}/models/{model}", e.g. "publishers/anthropic/models/claude-
   * opus-4-8" or "publishers/google/models/gemini-3-flash". Empty means the agent's default gemini
   * model.
   * @param model model or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1AgentModelConfig setModel(java.lang.String model) {
    this.model = model;
    return this;
  }

  /**
   * Optional. Sampling temperature for the model's generation config (valid range (0.0, 2.0]); a
   * value outside that range leaves the backend default standing.
   * @return value or {@code null} for none
   */
  public java.lang.Float getTemperature() {
    return temperature;
  }

  /**
   * Optional. Sampling temperature for the model's generation config (valid range (0.0, 2.0]); a
   * value outside that range leaves the backend default standing.
   * @param temperature temperature or {@code null} for none
   */
  public GoogleCloudAiplatformV1beta1AgentModelConfig setTemperature(java.lang.Float temperature) {
    this.temperature = temperature;
    return this;
  }

  @Override
  public GoogleCloudAiplatformV1beta1AgentModelConfig set(String fieldName, Object value) {
    return (GoogleCloudAiplatformV1beta1AgentModelConfig) super.set(fieldName, value);
  }

  @Override
  public GoogleCloudAiplatformV1beta1AgentModelConfig clone() {
    return (GoogleCloudAiplatformV1beta1AgentModelConfig) super.clone();
  }

}
