/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.drive.model;

/**
 * Request for reassigning an approval. Reviewers can be added or replaced, but not removed.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Drive API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ReassignApprovalRequest extends com.google.api.client.json.GenericJson {

  /**
   * Optional. The list of reviewers to add.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<AddReviewer> addReviewers;

  static {
    // hack to force ProGuard to consider AddReviewer used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(AddReviewer.class);
  }

  /**
   * Optional. A message to send to the new reviewers. This message is included in notifications for
   * the action and in the approval activity log.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String message;

  /**
   * Optional. The list of reviewer replacements.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<ReplaceReviewer> replaceReviewers;

  /**
   * Optional. The list of reviewers to add.
   * @return value or {@code null} for none
   */
  public java.util.List<AddReviewer> getAddReviewers() {
    return addReviewers;
  }

  /**
   * Optional. The list of reviewers to add.
   * @param addReviewers addReviewers or {@code null} for none
   */
  public ReassignApprovalRequest setAddReviewers(java.util.List<AddReviewer> addReviewers) {
    this.addReviewers = addReviewers;
    return this;
  }

  /**
   * Optional. A message to send to the new reviewers. This message is included in notifications for
   * the action and in the approval activity log.
   * @return value or {@code null} for none
   */
  public java.lang.String getMessage() {
    return message;
  }

  /**
   * Optional. A message to send to the new reviewers. This message is included in notifications for
   * the action and in the approval activity log.
   * @param message message or {@code null} for none
   */
  public ReassignApprovalRequest setMessage(java.lang.String message) {
    this.message = message;
    return this;
  }

  /**
   * Optional. The list of reviewer replacements.
   * @return value or {@code null} for none
   */
  public java.util.List<ReplaceReviewer> getReplaceReviewers() {
    return replaceReviewers;
  }

  /**
   * Optional. The list of reviewer replacements.
   * @param replaceReviewers replaceReviewers or {@code null} for none
   */
  public ReassignApprovalRequest setReplaceReviewers(java.util.List<ReplaceReviewer> replaceReviewers) {
    this.replaceReviewers = replaceReviewers;
    return this;
  }

  @Override
  public ReassignApprovalRequest set(String fieldName, Object value) {
    return (ReassignApprovalRequest) super.set(fieldName, value);
  }

  @Override
  public ReassignApprovalRequest clone() {
    return (ReassignApprovalRequest) super.clone();
  }

}
