/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.drive.model;

/**
 * Representation of a reviewer replacement.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Google Drive API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class ReplaceReviewer extends com.google.api.client.json.GenericJson {

  /**
   * Required. The email of the reviewer to add.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String addedReviewerEmail;

  /**
   * Required. The email of the reviewer to remove.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String removedReviewerEmail;

  /**
   * Required. The email of the reviewer to add.
   * @return value or {@code null} for none
   */
  public java.lang.String getAddedReviewerEmail() {
    return addedReviewerEmail;
  }

  /**
   * Required. The email of the reviewer to add.
   * @param addedReviewerEmail addedReviewerEmail or {@code null} for none
   */
  public ReplaceReviewer setAddedReviewerEmail(java.lang.String addedReviewerEmail) {
    this.addedReviewerEmail = addedReviewerEmail;
    return this;
  }

  /**
   * Required. The email of the reviewer to remove.
   * @return value or {@code null} for none
   */
  public java.lang.String getRemovedReviewerEmail() {
    return removedReviewerEmail;
  }

  /**
   * Required. The email of the reviewer to remove.
   * @param removedReviewerEmail removedReviewerEmail or {@code null} for none
   */
  public ReplaceReviewer setRemovedReviewerEmail(java.lang.String removedReviewerEmail) {
    this.removedReviewerEmail = removedReviewerEmail;
    return this;
  }

  @Override
  public ReplaceReviewer set(String fieldName, Object value) {
    return (ReplaceReviewer) super.set(fieldName, value);
  }

  @Override
  public ReplaceReviewer clone() {
    return (ReplaceReviewer) super.clone();
  }

}
