/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.securitycenter.v1.model;

/**
 * The http response returned by the web application.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Security Command Center API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HttpResponse extends com.google.api.client.json.GenericJson {

  /**
   * The http path for which response code was returned by web application, for example,
   * "https://test-app.a.run.app/test".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String path;

  /**
   * The http response code returned by the web application, for example, 200.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String statusCode;

  /**
   * The http path for which response code was returned by web application, for example,
   * "https://test-app.a.run.app/test".
   * @return value or {@code null} for none
   */
  public java.lang.String getPath() {
    return path;
  }

  /**
   * The http path for which response code was returned by web application, for example,
   * "https://test-app.a.run.app/test".
   * @param path path or {@code null} for none
   */
  public HttpResponse setPath(java.lang.String path) {
    this.path = path;
    return this;
  }

  /**
   * The http response code returned by the web application, for example, 200.
   * @return value or {@code null} for none
   */
  public java.lang.String getStatusCode() {
    return statusCode;
  }

  /**
   * The http response code returned by the web application, for example, 200.
   * @param statusCode statusCode or {@code null} for none
   */
  public HttpResponse setStatusCode(java.lang.String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  @Override
  public HttpResponse set(String fieldName, Object value) {
    return (HttpResponse) super.set(fieldName, value);
  }

  @Override
  public HttpResponse clone() {
    return (HttpResponse) super.clone();
  }

}
