/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.paymentsresellersubscription.v1.model;

/**
 * Request to suspend a subscription.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Payments Reseller Subscription API. For a detailed
 * explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class SuspendSubscriptionRequest extends com.google.api.client.json.GenericJson {

  /**
   * Optional. The mode to suspend the subscription. It's required for partners to specify the
   * suspend mode, whether suspend immediately and indefinitely, or cancel the subscription after
   * grace_period_millis or auto_cancel_duration_millis if it's not resumed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String suspendMode;

  /**
   * Optional. The mode to suspend the subscription. It's required for partners to specify the
   * suspend mode, whether suspend immediately and indefinitely, or cancel the subscription after
   * grace_period_millis or auto_cancel_duration_millis if it's not resumed.
   * @return value or {@code null} for none
   */
  public java.lang.String getSuspendMode() {
    return suspendMode;
  }

  /**
   * Optional. The mode to suspend the subscription. It's required for partners to specify the
   * suspend mode, whether suspend immediately and indefinitely, or cancel the subscription after
   * grace_period_millis or auto_cancel_duration_millis if it's not resumed.
   * @param suspendMode suspendMode or {@code null} for none
   */
  public SuspendSubscriptionRequest setSuspendMode(java.lang.String suspendMode) {
    this.suspendMode = suspendMode;
    return this;
  }

  @Override
  public SuspendSubscriptionRequest set(String fieldName, Object value) {
    return (SuspendSubscriptionRequest) super.set(fieldName, value);
  }

  @Override
  public SuspendSubscriptionRequest clone() {
    return (SuspendSubscriptionRequest) super.clone();
  }

}
