/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.merchantapi.products_v1.model;

/**
 * The energy consumption of the vehicle.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Merchant API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class EnergyConsumption extends com.google.api.client.json.GenericJson {

  /**
   * The unit of the energy consumption.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String unit;

  /**
   * The energy consumption value.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double value;

  /**
   * The unit of the energy consumption.
   * @return value or {@code null} for none
   */
  public java.lang.String getUnit() {
    return unit;
  }

  /**
   * The unit of the energy consumption.
   * @param unit unit or {@code null} for none
   */
  public EnergyConsumption setUnit(java.lang.String unit) {
    this.unit = unit;
    return this;
  }

  /**
   * The energy consumption value.
   * @return value or {@code null} for none
   */
  public java.lang.Double getValue() {
    return value;
  }

  /**
   * The energy consumption value.
   * @param value value or {@code null} for none
   */
  public EnergyConsumption setValue(java.lang.Double value) {
    this.value = value;
    return this;
  }

  @Override
  public EnergyConsumption set(String fieldName, Object value) {
    return (EnergyConsumption) super.set(fieldName, value);
  }

  @Override
  public EnergyConsumption clone() {
    return (EnergyConsumption) super.clone();
  }

}
