/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.merchantapi.products_v1.model;

/**
 * The warranty of the vehicle.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Merchant API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Warranty extends com.google.api.client.json.GenericJson {

  /**
   * The warranty duration in months.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long duration;

  /**
   * The warranty mileage.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Mileage mileage;

  /**
   * The warranty duration in months.
   * @return value or {@code null} for none
   */
  public java.lang.Long getDuration() {
    return duration;
  }

  /**
   * The warranty duration in months.
   * @param duration duration or {@code null} for none
   */
  public Warranty setDuration(java.lang.Long duration) {
    this.duration = duration;
    return this;
  }

  /**
   * The warranty mileage.
   * @return value or {@code null} for none
   */
  public Mileage getMileage() {
    return mileage;
  }

  /**
   * The warranty mileage.
   * @param mileage mileage or {@code null} for none
   */
  public Warranty setMileage(Mileage mileage) {
    this.mileage = mileage;
    return this;
  }

  @Override
  public Warranty set(String fieldName, Object value) {
    return (Warranty) super.set(fieldName, value);
  }

  @Override
  public Warranty clone() {
    return (Warranty) super.clone();
  }

}
