/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.file.v1beta1.model;

/**
 * Request for creating a volume from an existing data source (such as a backup).
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Filestore API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class CreateFromSourceRequest extends com.google.api.client.json.GenericJson {

  /**
   * The resource name of the backup to create from. Format:
   * projects/{project}/locations/{location}/backups/{backup}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String backup;

  /**
   * Optional. IP ACLs defining permissions/ACLs to apply to the newly created volume.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<NfsExportOptions> ipAcls;

  /**
   * Optional. The limit for how much data can be written to this volume, in MiB.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long quota;

  /**
   * Required. Unique identifier for the volume which also appears in the volumes resource name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String volumeId;

  /**
   * The resource name of the backup to create from. Format:
   * projects/{project}/locations/{location}/backups/{backup}
   * @return value or {@code null} for none
   */
  public java.lang.String getBackup() {
    return backup;
  }

  /**
   * The resource name of the backup to create from. Format:
   * projects/{project}/locations/{location}/backups/{backup}
   * @param backup backup or {@code null} for none
   */
  public CreateFromSourceRequest setBackup(java.lang.String backup) {
    this.backup = backup;
    return this;
  }

  /**
   * Optional. IP ACLs defining permissions/ACLs to apply to the newly created volume.
   * @return value or {@code null} for none
   */
  public java.util.List<NfsExportOptions> getIpAcls() {
    return ipAcls;
  }

  /**
   * Optional. IP ACLs defining permissions/ACLs to apply to the newly created volume.
   * @param ipAcls ipAcls or {@code null} for none
   */
  public CreateFromSourceRequest setIpAcls(java.util.List<NfsExportOptions> ipAcls) {
    this.ipAcls = ipAcls;
    return this;
  }

  /**
   * Optional. The limit for how much data can be written to this volume, in MiB.
   * @return value or {@code null} for none
   */
  public java.lang.Long getQuota() {
    return quota;
  }

  /**
   * Optional. The limit for how much data can be written to this volume, in MiB.
   * @param quota quota or {@code null} for none
   */
  public CreateFromSourceRequest setQuota(java.lang.Long quota) {
    this.quota = quota;
    return this;
  }

  /**
   * Required. Unique identifier for the volume which also appears in the volumes resource name.
   * @return value or {@code null} for none
   */
  public java.lang.String getVolumeId() {
    return volumeId;
  }

  /**
   * Required. Unique identifier for the volume which also appears in the volumes resource name.
   * @param volumeId volumeId or {@code null} for none
   */
  public CreateFromSourceRequest setVolumeId(java.lang.String volumeId) {
    this.volumeId = volumeId;
    return this;
  }

  @Override
  public CreateFromSourceRequest set(String fieldName, Object value) {
    return (CreateFromSourceRequest) super.set(fieldName, value);
  }

  @Override
  public CreateFromSourceRequest clone() {
    return (CreateFromSourceRequest) super.clone();
  }

}
