/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.file.v1beta1.model;

/**
 * Request for unfreezing a volume.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Filestore API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class UnfreezeVolumeRequest extends com.google.api.client.json.GenericJson {

  /**
   * Optional. IP ACLs defining permissions/ACLs to apply to the unfrozen volume
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<NfsExportOptions> ipAcls;

  static {
    // hack to force ProGuard to consider NfsExportOptions used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(NfsExportOptions.class);
  }

  /**
   * Optional. The limit for how much data can be written to this volume, in MiB.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long quota;

  /**
   * Optional. IP ACLs defining permissions/ACLs to apply to the unfrozen volume
   * @return value or {@code null} for none
   */
  public java.util.List<NfsExportOptions> getIpAcls() {
    return ipAcls;
  }

  /**
   * Optional. IP ACLs defining permissions/ACLs to apply to the unfrozen volume
   * @param ipAcls ipAcls or {@code null} for none
   */
  public UnfreezeVolumeRequest setIpAcls(java.util.List<NfsExportOptions> ipAcls) {
    this.ipAcls = ipAcls;
    return this;
  }

  /**
   * Optional. The limit for how much data can be written to this volume, in MiB.
   * @return value or {@code null} for none
   */
  public java.lang.Long getQuota() {
    return quota;
  }

  /**
   * Optional. The limit for how much data can be written to this volume, in MiB.
   * @param quota quota or {@code null} for none
   */
  public UnfreezeVolumeRequest setQuota(java.lang.Long quota) {
    this.quota = quota;
    return this;
  }

  @Override
  public UnfreezeVolumeRequest set(String fieldName, Object value) {
    return (UnfreezeVolumeRequest) super.set(fieldName, value);
  }

  @Override
  public UnfreezeVolumeRequest clone() {
    return (UnfreezeVolumeRequest) super.clone();
  }

}
