/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.file.v1beta1.model;

/**
 * Volume representation of a Cloud Filestore volume.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Cloud Filestore API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Volume extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The time when the volume was created.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String createTime;

  /**
   * Optional. A description of the volume with 2048 characters or less. Requests with longer
   * descriptions will be rejected.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * Optional. User-defined permissions protecting mount points.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<NfsExportOptions> ipAcls;

  static {
    // hack to force ProGuard to consider NfsExportOptions used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(NfsExportOptions.class);
  }

  /**
   * Optional. Resource labels to represent user provided metadata.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.lang.String> labels;

  /**
   * Output only. The mount point of the volume.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private MountPoint mountPoint;

  /**
   * Identifier. The resource name of the volume, in the format
   * `projects/{project}/locations/{location}/volumePools/{volume_pool}/volumes/{volume}`.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Optional. The maximum size of the volume in mebibytes (MiB).
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long quotaMib;

  /**
   * Optional. The state of the volume. This field is caller-settable via `UpdateVolume` to
   * transition a volume from `HOT` to `COLD` (freezing the volume). In `CreateVolume`, this field
   * is output-only and initialized to `HOT`.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * Output only. The time when the volume was created.
   * @return value or {@code null} for none
   */
  public String getCreateTime() {
    return createTime;
  }

  /**
   * Output only. The time when the volume was created.
   * @param createTime createTime or {@code null} for none
   */
  public Volume setCreateTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * Optional. A description of the volume with 2048 characters or less. Requests with longer
   * descriptions will be rejected.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Optional. A description of the volume with 2048 characters or less. Requests with longer
   * descriptions will be rejected.
   * @param description description or {@code null} for none
   */
  public Volume setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * Optional. User-defined permissions protecting mount points.
   * @return value or {@code null} for none
   */
  public java.util.List<NfsExportOptions> getIpAcls() {
    return ipAcls;
  }

  /**
   * Optional. User-defined permissions protecting mount points.
   * @param ipAcls ipAcls or {@code null} for none
   */
  public Volume setIpAcls(java.util.List<NfsExportOptions> ipAcls) {
    this.ipAcls = ipAcls;
    return this;
  }

  /**
   * Optional. Resource labels to represent user provided metadata.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.lang.String> getLabels() {
    return labels;
  }

  /**
   * Optional. Resource labels to represent user provided metadata.
   * @param labels labels or {@code null} for none
   */
  public Volume setLabels(java.util.Map<String, java.lang.String> labels) {
    this.labels = labels;
    return this;
  }

  /**
   * Output only. The mount point of the volume.
   * @return value or {@code null} for none
   */
  public MountPoint getMountPoint() {
    return mountPoint;
  }

  /**
   * Output only. The mount point of the volume.
   * @param mountPoint mountPoint or {@code null} for none
   */
  public Volume setMountPoint(MountPoint mountPoint) {
    this.mountPoint = mountPoint;
    return this;
  }

  /**
   * Identifier. The resource name of the volume, in the format
   * `projects/{project}/locations/{location}/volumePools/{volume_pool}/volumes/{volume}`.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Identifier. The resource name of the volume, in the format
   * `projects/{project}/locations/{location}/volumePools/{volume_pool}/volumes/{volume}`.
   * @param name name or {@code null} for none
   */
  public Volume setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Optional. The maximum size of the volume in mebibytes (MiB).
   * @return value or {@code null} for none
   */
  public java.lang.Long getQuotaMib() {
    return quotaMib;
  }

  /**
   * Optional. The maximum size of the volume in mebibytes (MiB).
   * @param quotaMib quotaMib or {@code null} for none
   */
  public Volume setQuotaMib(java.lang.Long quotaMib) {
    this.quotaMib = quotaMib;
    return this;
  }

  /**
   * Optional. The state of the volume. This field is caller-settable via `UpdateVolume` to
   * transition a volume from `HOT` to `COLD` (freezing the volume). In `CreateVolume`, this field
   * is output-only and initialized to `HOT`.
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * Optional. The state of the volume. This field is caller-settable via `UpdateVolume` to
   * transition a volume from `HOT` to `COLD` (freezing the volume). In `CreateVolume`, this field
   * is output-only and initialized to `HOT`.
   * @param state state or {@code null} for none
   */
  public Volume setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  @Override
  public Volume set(String fieldName, Object value) {
    return (Volume) super.set(fieldName, value);
  }

  @Override
  public Volume clone() {
    return (Volume) super.clone();
  }

}
