/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.gkehub.v1beta.model;

/**
 * Configuration for automatic upgrades.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the GKE Hub API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AutoUpgradeConfig extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Specifies the scope of automation for the creation of rollouts. Represents the types
   * of rollouts (version upgrades) the sequence should initiate automatically. If this field is
   * `unset`, it defaults to all types. If this field is `set` but the internal `upgrade_types` list
   * is `empty`, most automatic rollouts are disabled for this sequence. Exceptions are rollouts
   * enforcing our security policies (e.g. such as end-of-support and outdated control plane patch
   * enforcements). These policy enforcements cannot be disabled.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private RolloutCreationScope rolloutCreationScope;

  /**
   * Optional. Specifies the scope of automation for the creation of rollouts. Represents the types
   * of rollouts (version upgrades) the sequence should initiate automatically. If this field is
   * `unset`, it defaults to all types. If this field is `set` but the internal `upgrade_types` list
   * is `empty`, most automatic rollouts are disabled for this sequence. Exceptions are rollouts
   * enforcing our security policies (e.g. such as end-of-support and outdated control plane patch
   * enforcements). These policy enforcements cannot be disabled.
   * @return value or {@code null} for none
   */
  public RolloutCreationScope getRolloutCreationScope() {
    return rolloutCreationScope;
  }

  /**
   * Optional. Specifies the scope of automation for the creation of rollouts. Represents the types
   * of rollouts (version upgrades) the sequence should initiate automatically. If this field is
   * `unset`, it defaults to all types. If this field is `set` but the internal `upgrade_types` list
   * is `empty`, most automatic rollouts are disabled for this sequence. Exceptions are rollouts
   * enforcing our security policies (e.g. such as end-of-support and outdated control plane patch
   * enforcements). These policy enforcements cannot be disabled.
   * @param rolloutCreationScope rolloutCreationScope or {@code null} for none
   */
  public AutoUpgradeConfig setRolloutCreationScope(RolloutCreationScope rolloutCreationScope) {
    this.rolloutCreationScope = rolloutCreationScope;
    return this;
  }

  @Override
  public AutoUpgradeConfig set(String fieldName, Object value) {
    return (AutoUpgradeConfig) super.set(fieldName, value);
  }

  @Override
  public AutoUpgradeConfig clone() {
    return (AutoUpgradeConfig) super.clone();
  }

}
