/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Request to MoveChromeBrowsers method.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1MoveChromeBrowsersRequest extends com.google.api.client.json.GenericJson {

  /**
   * Required. ID of the destination organizational unit.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String destinationOrgUnitId;

  /**
   * Required. List of resource IDs of Chrome Browser Devices to move. A maximum of 600 browsers may
   * be moved per request.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> resourceIds;

  /**
   * Required. ID of the destination organizational unit.
   * @return value or {@code null} for none
   */
  public java.lang.String getDestinationOrgUnitId() {
    return destinationOrgUnitId;
  }

  /**
   * Required. ID of the destination organizational unit.
   * @param destinationOrgUnitId destinationOrgUnitId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1MoveChromeBrowsersRequest setDestinationOrgUnitId(java.lang.String destinationOrgUnitId) {
    this.destinationOrgUnitId = destinationOrgUnitId;
    return this;
  }

  /**
   * Required. List of resource IDs of Chrome Browser Devices to move. A maximum of 600 browsers may
   * be moved per request.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getResourceIds() {
    return resourceIds;
  }

  /**
   * Required. List of resource IDs of Chrome Browser Devices to move. A maximum of 600 browsers may
   * be moved per request.
   * @param resourceIds resourceIds or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1MoveChromeBrowsersRequest setResourceIds(java.util.List<java.lang.String> resourceIds) {
    this.resourceIds = resourceIds;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1MoveChromeBrowsersRequest set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1MoveChromeBrowsersRequest) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1MoveChromeBrowsersRequest clone() {
    return (GoogleChromeManagementVersionsV1MoveChromeBrowsersRequest) super.clone();
  }

}
