/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Information about extensions installed on profile reported on an installed Chrome on a device
 * with managed chrome browsers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1Extension extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The type of the extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String appType;

  /**
   * Output only. If the extension is controlled by a browser policy.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String configuredAppPolicy;

  /**
   * Output only. The localized description of this extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * Output only. Whether the extension is disabled.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean disabled;

  /**
   * Output only. The id of the extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String extensionId;

  /**
   * Output only. The localized name of this extension as reported by Chrome.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String extensionName;

  /**
   * Output only. The URL of the homepage for this extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String homepageUri;

  /**
   * Output only. The list of icons available for this extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1ExtensionIcon> icons;

  /**
   * Output only. The way the extension was installed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String installType;

  /**
   * Output only. The manifest version of this extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer manifestVersion;

  /**
   * Output only. The list of permissions required for this extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> permissions;

  /**
   * Output only. The version of the extension.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String version;

  /**
   * Output only. The type of the extension.
   * @return value or {@code null} for none
   */
  public java.lang.String getAppType() {
    return appType;
  }

  /**
   * Output only. The type of the extension.
   * @param appType appType or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setAppType(java.lang.String appType) {
    this.appType = appType;
    return this;
  }

  /**
   * Output only. If the extension is controlled by a browser policy.
   * @return value or {@code null} for none
   */
  public java.lang.String getConfiguredAppPolicy() {
    return configuredAppPolicy;
  }

  /**
   * Output only. If the extension is controlled by a browser policy.
   * @param configuredAppPolicy configuredAppPolicy or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setConfiguredAppPolicy(java.lang.String configuredAppPolicy) {
    this.configuredAppPolicy = configuredAppPolicy;
    return this;
  }

  /**
   * Output only. The localized description of this extension.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Output only. The localized description of this extension.
   * @param description description or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * Output only. Whether the extension is disabled.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDisabled() {
    return disabled;
  }

  /**
   * Output only. Whether the extension is disabled.
   * @param disabled disabled or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setDisabled(java.lang.Boolean disabled) {
    this.disabled = disabled;
    return this;
  }

  /**
   * Output only. The id of the extension.
   * @return value or {@code null} for none
   */
  public java.lang.String getExtensionId() {
    return extensionId;
  }

  /**
   * Output only. The id of the extension.
   * @param extensionId extensionId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setExtensionId(java.lang.String extensionId) {
    this.extensionId = extensionId;
    return this;
  }

  /**
   * Output only. The localized name of this extension as reported by Chrome.
   * @return value or {@code null} for none
   */
  public java.lang.String getExtensionName() {
    return extensionName;
  }

  /**
   * Output only. The localized name of this extension as reported by Chrome.
   * @param extensionName extensionName or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setExtensionName(java.lang.String extensionName) {
    this.extensionName = extensionName;
    return this;
  }

  /**
   * Output only. The URL of the homepage for this extension.
   * @return value or {@code null} for none
   */
  public java.lang.String getHomepageUri() {
    return homepageUri;
  }

  /**
   * Output only. The URL of the homepage for this extension.
   * @param homepageUri homepageUri or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setHomepageUri(java.lang.String homepageUri) {
    this.homepageUri = homepageUri;
    return this;
  }

  /**
   * Output only. The list of icons available for this extension.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1ExtensionIcon> getIcons() {
    return icons;
  }

  /**
   * Output only. The list of icons available for this extension.
   * @param icons icons or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setIcons(java.util.List<GoogleChromeManagementVersionsV1ExtensionIcon> icons) {
    this.icons = icons;
    return this;
  }

  /**
   * Output only. The way the extension was installed.
   * @return value or {@code null} for none
   */
  public java.lang.String getInstallType() {
    return installType;
  }

  /**
   * Output only. The way the extension was installed.
   * @param installType installType or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setInstallType(java.lang.String installType) {
    this.installType = installType;
    return this;
  }

  /**
   * Output only. The manifest version of this extension.
   * @return value or {@code null} for none
   */
  public java.lang.Integer getManifestVersion() {
    return manifestVersion;
  }

  /**
   * Output only. The manifest version of this extension.
   * @param manifestVersion manifestVersion or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setManifestVersion(java.lang.Integer manifestVersion) {
    this.manifestVersion = manifestVersion;
    return this;
  }

  /**
   * Output only. The list of permissions required for this extension.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getPermissions() {
    return permissions;
  }

  /**
   * Output only. The list of permissions required for this extension.
   * @param permissions permissions or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setPermissions(java.util.List<java.lang.String> permissions) {
    this.permissions = permissions;
    return this;
  }

  /**
   * Output only. The version of the extension.
   * @return value or {@code null} for none
   */
  public java.lang.String getVersion() {
    return version;
  }

  /**
   * Output only. The version of the extension.
   * @param version version or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Extension setVersion(java.lang.String version) {
    this.version = version;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1Extension set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1Extension) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1Extension clone() {
    return (GoogleChromeManagementVersionsV1Extension) super.clone();
  }

}
