/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * A specific installation of Chrome on a device with managed Chrome browsers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1Browser extends com.google.api.client.json.GenericJson {

  /**
   * Output only. Browser version installed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String browserVersion;

  /**
   * Output only. The channel of the browser installed.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String channel;

  /**
   * Output only. The path to the Chrome.exe executable for this browser.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String executablePath;

  /**
   * Output only. The time when the last request to fetch policies succeeded on this Chrome browser.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastPolicyFetchTime;

  /**
   * Output only. The time when the last report was received from this Chrome browser.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastStatusReportTime;

  /**
   * Output only. Pending version of a browser is installed. This field is only set when the current
   * active browser has a different version as in "browser_version".
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pendingInstallVersion;

  /**
   * Output only. List of all plugins installed on this Chrome browser.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1Plugin> plugins;

  /**
   * Output only. The list of profiles for this browser.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1Profile> profiles;

  /**
   * Output only. Browser version installed.
   * @return value or {@code null} for none
   */
  public java.lang.String getBrowserVersion() {
    return browserVersion;
  }

  /**
   * Output only. Browser version installed.
   * @param browserVersion browserVersion or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setBrowserVersion(java.lang.String browserVersion) {
    this.browserVersion = browserVersion;
    return this;
  }

  /**
   * Output only. The channel of the browser installed.
   * @return value or {@code null} for none
   */
  public java.lang.String getChannel() {
    return channel;
  }

  /**
   * Output only. The channel of the browser installed.
   * @param channel channel or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setChannel(java.lang.String channel) {
    this.channel = channel;
    return this;
  }

  /**
   * Output only. The path to the Chrome.exe executable for this browser.
   * @return value or {@code null} for none
   */
  public java.lang.String getExecutablePath() {
    return executablePath;
  }

  /**
   * Output only. The path to the Chrome.exe executable for this browser.
   * @param executablePath executablePath or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setExecutablePath(java.lang.String executablePath) {
    this.executablePath = executablePath;
    return this;
  }

  /**
   * Output only. The time when the last request to fetch policies succeeded on this Chrome browser.
   * @return value or {@code null} for none
   */
  public String getLastPolicyFetchTime() {
    return lastPolicyFetchTime;
  }

  /**
   * Output only. The time when the last request to fetch policies succeeded on this Chrome browser.
   * @param lastPolicyFetchTime lastPolicyFetchTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setLastPolicyFetchTime(String lastPolicyFetchTime) {
    this.lastPolicyFetchTime = lastPolicyFetchTime;
    return this;
  }

  /**
   * Output only. The time when the last report was received from this Chrome browser.
   * @return value or {@code null} for none
   */
  public String getLastStatusReportTime() {
    return lastStatusReportTime;
  }

  /**
   * Output only. The time when the last report was received from this Chrome browser.
   * @param lastStatusReportTime lastStatusReportTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setLastStatusReportTime(String lastStatusReportTime) {
    this.lastStatusReportTime = lastStatusReportTime;
    return this;
  }

  /**
   * Output only. Pending version of a browser is installed. This field is only set when the current
   * active browser has a different version as in "browser_version".
   * @return value or {@code null} for none
   */
  public java.lang.String getPendingInstallVersion() {
    return pendingInstallVersion;
  }

  /**
   * Output only. Pending version of a browser is installed. This field is only set when the current
   * active browser has a different version as in "browser_version".
   * @param pendingInstallVersion pendingInstallVersion or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setPendingInstallVersion(java.lang.String pendingInstallVersion) {
    this.pendingInstallVersion = pendingInstallVersion;
    return this;
  }

  /**
   * Output only. List of all plugins installed on this Chrome browser.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1Plugin> getPlugins() {
    return plugins;
  }

  /**
   * Output only. List of all plugins installed on this Chrome browser.
   * @param plugins plugins or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setPlugins(java.util.List<GoogleChromeManagementVersionsV1Plugin> plugins) {
    this.plugins = plugins;
    return this;
  }

  /**
   * Output only. The list of profiles for this browser.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1Profile> getProfiles() {
    return profiles;
  }

  /**
   * Output only. The list of profiles for this browser.
   * @param profiles profiles or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Browser setProfiles(java.util.List<GoogleChromeManagementVersionsV1Profile> profiles) {
    this.profiles = profiles;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1Browser set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1Browser) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1Browser clone() {
    return (GoogleChromeManagementVersionsV1Browser) super.clone();
  }

}
