/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Enrollment token for a chrome device.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1EnrollmentToken extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The creation time of the token.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String createTime;

  /**
   * Output only. The id of the user who created the token.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String creatorId;

  /**
   * Output only. The obfuscated ID of the customer to whom this token is associated.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String customerId;

  /**
   * Identifier. The resource name of the enrollment token. Format:
   * customers/{customer}/enrollmentTokens/{token_permanent_id}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Optional. Obfuscated ID of the organization unit this token is associated with. If not set, the
   * token is created for the root organization unit.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String orgUnitId;

  /**
   * Output only. The revocation time of the token, null if the token is not revoked.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String revokeTime;

  /**
   * Output only. The id of the user who revoked the token, null if the token is not revoked.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String revokerId;

  /**
   * Output only. The state of the token.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * Output only. The value of the token stored on the device and used to identify it to the
   * management service handling the enrollment request.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String token;

  /**
   * Output only. Unique identifier of the enrollment token used to access information on tokens.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tokenPermanentId;

  /**
   * Optional. The device type this token is used for. If not set, defaults to
   * `ENROLLMENT_TOKEN_TYPE_CHROME_BROWSER`.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String tokenType;

  /**
   * Output only. The creation time of the token.
   * @return value or {@code null} for none
   */
  public String getCreateTime() {
    return createTime;
  }

  /**
   * Output only. The creation time of the token.
   * @param createTime createTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setCreateTime(String createTime) {
    this.createTime = createTime;
    return this;
  }

  /**
   * Output only. The id of the user who created the token.
   * @return value or {@code null} for none
   */
  public java.lang.String getCreatorId() {
    return creatorId;
  }

  /**
   * Output only. The id of the user who created the token.
   * @param creatorId creatorId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setCreatorId(java.lang.String creatorId) {
    this.creatorId = creatorId;
    return this;
  }

  /**
   * Output only. The obfuscated ID of the customer to whom this token is associated.
   * @return value or {@code null} for none
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }

  /**
   * Output only. The obfuscated ID of the customer to whom this token is associated.
   * @param customerId customerId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setCustomerId(java.lang.String customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Identifier. The resource name of the enrollment token. Format:
   * customers/{customer}/enrollmentTokens/{token_permanent_id}
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Identifier. The resource name of the enrollment token. Format:
   * customers/{customer}/enrollmentTokens/{token_permanent_id}
   * @param name name or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Optional. Obfuscated ID of the organization unit this token is associated with. If not set, the
   * token is created for the root organization unit.
   * @return value or {@code null} for none
   */
  public java.lang.String getOrgUnitId() {
    return orgUnitId;
  }

  /**
   * Optional. Obfuscated ID of the organization unit this token is associated with. If not set, the
   * token is created for the root organization unit.
   * @param orgUnitId orgUnitId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setOrgUnitId(java.lang.String orgUnitId) {
    this.orgUnitId = orgUnitId;
    return this;
  }

  /**
   * Output only. The revocation time of the token, null if the token is not revoked.
   * @return value or {@code null} for none
   */
  public String getRevokeTime() {
    return revokeTime;
  }

  /**
   * Output only. The revocation time of the token, null if the token is not revoked.
   * @param revokeTime revokeTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setRevokeTime(String revokeTime) {
    this.revokeTime = revokeTime;
    return this;
  }

  /**
   * Output only. The id of the user who revoked the token, null if the token is not revoked.
   * @return value or {@code null} for none
   */
  public java.lang.String getRevokerId() {
    return revokerId;
  }

  /**
   * Output only. The id of the user who revoked the token, null if the token is not revoked.
   * @param revokerId revokerId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setRevokerId(java.lang.String revokerId) {
    this.revokerId = revokerId;
    return this;
  }

  /**
   * Output only. The state of the token.
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * Output only. The state of the token.
   * @param state state or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  /**
   * Output only. The value of the token stored on the device and used to identify it to the
   * management service handling the enrollment request.
   * @return value or {@code null} for none
   */
  public java.lang.String getToken() {
    return token;
  }

  /**
   * Output only. The value of the token stored on the device and used to identify it to the
   * management service handling the enrollment request.
   * @param token token or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setToken(java.lang.String token) {
    this.token = token;
    return this;
  }

  /**
   * Output only. Unique identifier of the enrollment token used to access information on tokens.
   * @return value or {@code null} for none
   */
  public java.lang.String getTokenPermanentId() {
    return tokenPermanentId;
  }

  /**
   * Output only. Unique identifier of the enrollment token used to access information on tokens.
   * @param tokenPermanentId tokenPermanentId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setTokenPermanentId(java.lang.String tokenPermanentId) {
    this.tokenPermanentId = tokenPermanentId;
    return this;
  }

  /**
   * Optional. The device type this token is used for. If not set, defaults to
   * `ENROLLMENT_TOKEN_TYPE_CHROME_BROWSER`.
   * @return value or {@code null} for none
   */
  public java.lang.String getTokenType() {
    return tokenType;
  }

  /**
   * Optional. The device type this token is used for. If not set, defaults to
   * `ENROLLMENT_TOKEN_TYPE_CHROME_BROWSER`.
   * @param tokenType tokenType or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1EnrollmentToken setTokenType(java.lang.String tokenType) {
    this.tokenType = tokenType;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1EnrollmentToken set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1EnrollmentToken) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1EnrollmentToken clone() {
    return (GoogleChromeManagementVersionsV1EnrollmentToken) super.clone();
  }

}
