/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Response to ListChromeBrowsers method.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1ListChromeBrowsersResponse extends com.google.api.client.json.GenericJson {

  /**
   * List of Chrome Browser device objects.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1ChromeBrowser> chromeBrowsers;

  static {
    // hack to force ProGuard to consider GoogleChromeManagementVersionsV1ChromeBrowser used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleChromeManagementVersionsV1ChromeBrowser.class);
  }

  /**
   * Token used to access next page of this result.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nextPageToken;

  /**
   * List of Chrome Browser device objects.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1ChromeBrowser> getChromeBrowsers() {
    return chromeBrowsers;
  }

  /**
   * List of Chrome Browser device objects.
   * @param chromeBrowsers chromeBrowsers or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ListChromeBrowsersResponse setChromeBrowsers(java.util.List<GoogleChromeManagementVersionsV1ChromeBrowser> chromeBrowsers) {
    this.chromeBrowsers = chromeBrowsers;
    return this;
  }

  /**
   * Token used to access next page of this result.
   * @return value or {@code null} for none
   */
  public java.lang.String getNextPageToken() {
    return nextPageToken;
  }

  /**
   * Token used to access next page of this result.
   * @param nextPageToken nextPageToken or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ListChromeBrowsersResponse setNextPageToken(java.lang.String nextPageToken) {
    this.nextPageToken = nextPageToken;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1ListChromeBrowsersResponse set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1ListChromeBrowsersResponse) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1ListChromeBrowsersResponse clone() {
    return (GoogleChromeManagementVersionsV1ListChromeBrowsersResponse) super.clone();
  }

}
