/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * A profile reported on an installation of Chrome on a device with managed chrome browsers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1Profile extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The email of the user signed in to this profile, if any.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String chromeSignedInUserEmail;

  /**
   * Output only. The list of extensions with applied extension policies.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1ExtensionPolicy> extensionPolicies;

  static {
    // hack to force ProGuard to consider GoogleChromeManagementVersionsV1ExtensionPolicy used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleChromeManagementVersionsV1ExtensionPolicy.class);
  }

  /**
   * Output only. The list of extensions installed for this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1Extension> extensions;

  static {
    // hack to force ProGuard to consider GoogleChromeManagementVersionsV1Extension used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleChromeManagementVersionsV1Extension.class);
  }

  /**
   * Output only. A unique ID for this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * Output only. The time when the last request to fetch policies succeeded for this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastPolicyFetchTime;

  /**
   * Output only. The time when the last report was received from this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastStatusReportTime;

  /**
   * Output only. The name given to this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String profileName;

  /**
   * Output only. The number of safe browsing warnings that were shown on this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long safeBrowsingWarnings;

  /**
   * Output only. The number of safe browsing warnings that were clicked through on this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long safeBrowsingWarningsClickThroughs;

  /**
   * Output only. The last time the safe browsing warning info was reset to 0.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String safeBrowsingWarningsResetTime;

  /**
   * Output only. The list of Chrome browser policies applied to this profile.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1Policy> userPolicies;

  static {
    // hack to force ProGuard to consider GoogleChromeManagementVersionsV1Policy used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleChromeManagementVersionsV1Policy.class);
  }

  /**
   * Output only. The email of the user signed in to this profile, if any.
   * @return value or {@code null} for none
   */
  public java.lang.String getChromeSignedInUserEmail() {
    return chromeSignedInUserEmail;
  }

  /**
   * Output only. The email of the user signed in to this profile, if any.
   * @param chromeSignedInUserEmail chromeSignedInUserEmail or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setChromeSignedInUserEmail(java.lang.String chromeSignedInUserEmail) {
    this.chromeSignedInUserEmail = chromeSignedInUserEmail;
    return this;
  }

  /**
   * Output only. The list of extensions with applied extension policies.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1ExtensionPolicy> getExtensionPolicies() {
    return extensionPolicies;
  }

  /**
   * Output only. The list of extensions with applied extension policies.
   * @param extensionPolicies extensionPolicies or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setExtensionPolicies(java.util.List<GoogleChromeManagementVersionsV1ExtensionPolicy> extensionPolicies) {
    this.extensionPolicies = extensionPolicies;
    return this;
  }

  /**
   * Output only. The list of extensions installed for this profile.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1Extension> getExtensions() {
    return extensions;
  }

  /**
   * Output only. The list of extensions installed for this profile.
   * @param extensions extensions or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setExtensions(java.util.List<GoogleChromeManagementVersionsV1Extension> extensions) {
    this.extensions = extensions;
    return this;
  }

  /**
   * Output only. A unique ID for this profile.
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * Output only. A unique ID for this profile.
   * @param id id or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * Output only. The time when the last request to fetch policies succeeded for this profile.
   * @return value or {@code null} for none
   */
  public String getLastPolicyFetchTime() {
    return lastPolicyFetchTime;
  }

  /**
   * Output only. The time when the last request to fetch policies succeeded for this profile.
   * @param lastPolicyFetchTime lastPolicyFetchTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setLastPolicyFetchTime(String lastPolicyFetchTime) {
    this.lastPolicyFetchTime = lastPolicyFetchTime;
    return this;
  }

  /**
   * Output only. The time when the last report was received from this profile.
   * @return value or {@code null} for none
   */
  public String getLastStatusReportTime() {
    return lastStatusReportTime;
  }

  /**
   * Output only. The time when the last report was received from this profile.
   * @param lastStatusReportTime lastStatusReportTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setLastStatusReportTime(String lastStatusReportTime) {
    this.lastStatusReportTime = lastStatusReportTime;
    return this;
  }

  /**
   * Output only. The name given to this profile.
   * @return value or {@code null} for none
   */
  public java.lang.String getProfileName() {
    return profileName;
  }

  /**
   * Output only. The name given to this profile.
   * @param profileName profileName or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setProfileName(java.lang.String profileName) {
    this.profileName = profileName;
    return this;
  }

  /**
   * Output only. The number of safe browsing warnings that were shown on this profile.
   * @return value or {@code null} for none
   */
  public java.lang.Long getSafeBrowsingWarnings() {
    return safeBrowsingWarnings;
  }

  /**
   * Output only. The number of safe browsing warnings that were shown on this profile.
   * @param safeBrowsingWarnings safeBrowsingWarnings or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setSafeBrowsingWarnings(java.lang.Long safeBrowsingWarnings) {
    this.safeBrowsingWarnings = safeBrowsingWarnings;
    return this;
  }

  /**
   * Output only. The number of safe browsing warnings that were clicked through on this profile.
   * @return value or {@code null} for none
   */
  public java.lang.Long getSafeBrowsingWarningsClickThroughs() {
    return safeBrowsingWarningsClickThroughs;
  }

  /**
   * Output only. The number of safe browsing warnings that were clicked through on this profile.
   * @param safeBrowsingWarningsClickThroughs safeBrowsingWarningsClickThroughs or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setSafeBrowsingWarningsClickThroughs(java.lang.Long safeBrowsingWarningsClickThroughs) {
    this.safeBrowsingWarningsClickThroughs = safeBrowsingWarningsClickThroughs;
    return this;
  }

  /**
   * Output only. The last time the safe browsing warning info was reset to 0.
   * @return value or {@code null} for none
   */
  public String getSafeBrowsingWarningsResetTime() {
    return safeBrowsingWarningsResetTime;
  }

  /**
   * Output only. The last time the safe browsing warning info was reset to 0.
   * @param safeBrowsingWarningsResetTime safeBrowsingWarningsResetTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setSafeBrowsingWarningsResetTime(String safeBrowsingWarningsResetTime) {
    this.safeBrowsingWarningsResetTime = safeBrowsingWarningsResetTime;
    return this;
  }

  /**
   * Output only. The list of Chrome browser policies applied to this profile.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1Policy> getUserPolicies() {
    return userPolicies;
  }

  /**
   * Output only. The list of Chrome browser policies applied to this profile.
   * @param userPolicies userPolicies or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Profile setUserPolicies(java.util.List<GoogleChromeManagementVersionsV1Policy> userPolicies) {
    this.userPolicies = userPolicies;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1Profile set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1Profile) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1Profile clone() {
    return (GoogleChromeManagementVersionsV1Profile) super.clone();
  }

}
