/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * A device with managed Chrome Browsers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1ChromeBrowser extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Asset identifier as annotated by the administrator or specified during enrollment.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String annotatedAssetId;

  /**
   * Optional. Address or location of the device as annotated by the administrator.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String annotatedLocation;

  /**
   * Optional. Notes about this device as annotated by the administrator.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String annotatedNotes;

  /**
   * Optional. User of the device as annotated by the administrator.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String annotatedUser;

  /**
   * Output only. The attestation credential used for Device Trust Connector.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleChromeManagementVersionsV1AttestationCredential attestationCredential;

  /**
   * Output only. Unique identifier of Chrome Browser.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String browserPermanentId;

  /**
   * Output only. List of all browser versions installed on this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> browserVersions;

  /**
   * Output only. List of Chrome browsers installed on this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1Browser> browsers;

  static {
    // hack to force ProGuard to consider GoogleChromeManagementVersionsV1Browser used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleChromeManagementVersionsV1Browser.class);
  }

  /**
   * Output only. The history of identifiers reported to this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleChromeManagementVersionsV1DeviceIdentifiersHistory deviceIdentifiersHistory;

  /**
   * Output only. The number of distinct extensions installed on all the Chrome browsers of this
   * device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long extensionCount;

  /**
   * Output only. The time of the last activity on the device device either from reporting, policy
   * fetching or registration.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastActivityTime;

  /**
   * Output only. The last user who logged into a Chrome browser on this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String lastDeviceUser;

  /**
   * Output only. List of recent browser users, in descending order by last report time.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1BrowserUser> lastDeviceUsers;

  static {
    // hack to force ProGuard to consider GoogleChromeManagementVersionsV1BrowserUser used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(GoogleChromeManagementVersionsV1BrowserUser.class);
  }

  /**
   * Output only. The time the last policy fetch succeeded on this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastPolicyFetchTime;

  /**
   * Output only. The time the device last tried to register.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastRegistrationTime;

  /**
   * Output only. The time the device last sent a status report.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastStatusReportTime;

  /**
   * Output only. The list of all device level policies set for extensions installed in Chrome on
   * this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1ExtensionPolicy> machineExtensionPolicies;

  /**
   * Output only. Machine name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String machineName;

  /**
   * Output only. The list of all device level policies set for Chrome browsers on this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1Policy> machinePolicies;

  /**
   * Identifier. Format: customers/{customer_id}/chromeBrowsers/{browser_permanent_id}
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Output only. Recent policy fetch activity by Omaha. Not necessarily the last fetch since this
   * field is only updated daily.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String omahaRecentFetchTime;

  /**
   * Output only. The obfuscated organizational unit ID of the browser.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String orgUnitId;

  /**
   * Output only. Device CPU architecture.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String osArchitecture;

  /**
   * Output only. Device Os platform.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String osPlatform;

  /**
   * Output only. Device Os platform and version combined.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String osPlatformVersion;

  /**
   * Output only. Device Os Version.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String osVersion;

  /**
   * Output only. The number of distinct policies set on all the Chrome browsers of this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long policyCount;

  /**
   * Output only. The device's serial number.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String serialNumber;

  /**
   * Output only. The initial device id sent by the first Chrome browser that enrolled this device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String virtualDeviceId;

  /**
   * Optional. Asset identifier as annotated by the administrator or specified during enrollment.
   * @return value or {@code null} for none
   */
  public java.lang.String getAnnotatedAssetId() {
    return annotatedAssetId;
  }

  /**
   * Optional. Asset identifier as annotated by the administrator or specified during enrollment.
   * @param annotatedAssetId annotatedAssetId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setAnnotatedAssetId(java.lang.String annotatedAssetId) {
    this.annotatedAssetId = annotatedAssetId;
    return this;
  }

  /**
   * Optional. Address or location of the device as annotated by the administrator.
   * @return value or {@code null} for none
   */
  public java.lang.String getAnnotatedLocation() {
    return annotatedLocation;
  }

  /**
   * Optional. Address or location of the device as annotated by the administrator.
   * @param annotatedLocation annotatedLocation or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setAnnotatedLocation(java.lang.String annotatedLocation) {
    this.annotatedLocation = annotatedLocation;
    return this;
  }

  /**
   * Optional. Notes about this device as annotated by the administrator.
   * @return value or {@code null} for none
   */
  public java.lang.String getAnnotatedNotes() {
    return annotatedNotes;
  }

  /**
   * Optional. Notes about this device as annotated by the administrator.
   * @param annotatedNotes annotatedNotes or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setAnnotatedNotes(java.lang.String annotatedNotes) {
    this.annotatedNotes = annotatedNotes;
    return this;
  }

  /**
   * Optional. User of the device as annotated by the administrator.
   * @return value or {@code null} for none
   */
  public java.lang.String getAnnotatedUser() {
    return annotatedUser;
  }

  /**
   * Optional. User of the device as annotated by the administrator.
   * @param annotatedUser annotatedUser or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setAnnotatedUser(java.lang.String annotatedUser) {
    this.annotatedUser = annotatedUser;
    return this;
  }

  /**
   * Output only. The attestation credential used for Device Trust Connector.
   * @return value or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1AttestationCredential getAttestationCredential() {
    return attestationCredential;
  }

  /**
   * Output only. The attestation credential used for Device Trust Connector.
   * @param attestationCredential attestationCredential or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setAttestationCredential(GoogleChromeManagementVersionsV1AttestationCredential attestationCredential) {
    this.attestationCredential = attestationCredential;
    return this;
  }

  /**
   * Output only. Unique identifier of Chrome Browser.
   * @return value or {@code null} for none
   */
  public java.lang.String getBrowserPermanentId() {
    return browserPermanentId;
  }

  /**
   * Output only. Unique identifier of Chrome Browser.
   * @param browserPermanentId browserPermanentId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setBrowserPermanentId(java.lang.String browserPermanentId) {
    this.browserPermanentId = browserPermanentId;
    return this;
  }

  /**
   * Output only. List of all browser versions installed on this device.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getBrowserVersions() {
    return browserVersions;
  }

  /**
   * Output only. List of all browser versions installed on this device.
   * @param browserVersions browserVersions or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setBrowserVersions(java.util.List<java.lang.String> browserVersions) {
    this.browserVersions = browserVersions;
    return this;
  }

  /**
   * Output only. List of Chrome browsers installed on this device.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1Browser> getBrowsers() {
    return browsers;
  }

  /**
   * Output only. List of Chrome browsers installed on this device.
   * @param browsers browsers or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setBrowsers(java.util.List<GoogleChromeManagementVersionsV1Browser> browsers) {
    this.browsers = browsers;
    return this;
  }

  /**
   * Output only. The history of identifiers reported to this device.
   * @return value or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiersHistory getDeviceIdentifiersHistory() {
    return deviceIdentifiersHistory;
  }

  /**
   * Output only. The history of identifiers reported to this device.
   * @param deviceIdentifiersHistory deviceIdentifiersHistory or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setDeviceIdentifiersHistory(GoogleChromeManagementVersionsV1DeviceIdentifiersHistory deviceIdentifiersHistory) {
    this.deviceIdentifiersHistory = deviceIdentifiersHistory;
    return this;
  }

  /**
   * Output only. The number of distinct extensions installed on all the Chrome browsers of this
   * device.
   * @return value or {@code null} for none
   */
  public java.lang.Long getExtensionCount() {
    return extensionCount;
  }

  /**
   * Output only. The number of distinct extensions installed on all the Chrome browsers of this
   * device.
   * @param extensionCount extensionCount or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setExtensionCount(java.lang.Long extensionCount) {
    this.extensionCount = extensionCount;
    return this;
  }

  /**
   * Output only. The time of the last activity on the device device either from reporting, policy
   * fetching or registration.
   * @return value or {@code null} for none
   */
  public String getLastActivityTime() {
    return lastActivityTime;
  }

  /**
   * Output only. The time of the last activity on the device device either from reporting, policy
   * fetching or registration.
   * @param lastActivityTime lastActivityTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setLastActivityTime(String lastActivityTime) {
    this.lastActivityTime = lastActivityTime;
    return this;
  }

  /**
   * Output only. The last user who logged into a Chrome browser on this device.
   * @return value or {@code null} for none
   */
  public java.lang.String getLastDeviceUser() {
    return lastDeviceUser;
  }

  /**
   * Output only. The last user who logged into a Chrome browser on this device.
   * @param lastDeviceUser lastDeviceUser or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setLastDeviceUser(java.lang.String lastDeviceUser) {
    this.lastDeviceUser = lastDeviceUser;
    return this;
  }

  /**
   * Output only. List of recent browser users, in descending order by last report time.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1BrowserUser> getLastDeviceUsers() {
    return lastDeviceUsers;
  }

  /**
   * Output only. List of recent browser users, in descending order by last report time.
   * @param lastDeviceUsers lastDeviceUsers or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setLastDeviceUsers(java.util.List<GoogleChromeManagementVersionsV1BrowserUser> lastDeviceUsers) {
    this.lastDeviceUsers = lastDeviceUsers;
    return this;
  }

  /**
   * Output only. The time the last policy fetch succeeded on this device.
   * @return value or {@code null} for none
   */
  public String getLastPolicyFetchTime() {
    return lastPolicyFetchTime;
  }

  /**
   * Output only. The time the last policy fetch succeeded on this device.
   * @param lastPolicyFetchTime lastPolicyFetchTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setLastPolicyFetchTime(String lastPolicyFetchTime) {
    this.lastPolicyFetchTime = lastPolicyFetchTime;
    return this;
  }

  /**
   * Output only. The time the device last tried to register.
   * @return value or {@code null} for none
   */
  public String getLastRegistrationTime() {
    return lastRegistrationTime;
  }

  /**
   * Output only. The time the device last tried to register.
   * @param lastRegistrationTime lastRegistrationTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setLastRegistrationTime(String lastRegistrationTime) {
    this.lastRegistrationTime = lastRegistrationTime;
    return this;
  }

  /**
   * Output only. The time the device last sent a status report.
   * @return value or {@code null} for none
   */
  public String getLastStatusReportTime() {
    return lastStatusReportTime;
  }

  /**
   * Output only. The time the device last sent a status report.
   * @param lastStatusReportTime lastStatusReportTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setLastStatusReportTime(String lastStatusReportTime) {
    this.lastStatusReportTime = lastStatusReportTime;
    return this;
  }

  /**
   * Output only. The list of all device level policies set for extensions installed in Chrome on
   * this device.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1ExtensionPolicy> getMachineExtensionPolicies() {
    return machineExtensionPolicies;
  }

  /**
   * Output only. The list of all device level policies set for extensions installed in Chrome on
   * this device.
   * @param machineExtensionPolicies machineExtensionPolicies or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setMachineExtensionPolicies(java.util.List<GoogleChromeManagementVersionsV1ExtensionPolicy> machineExtensionPolicies) {
    this.machineExtensionPolicies = machineExtensionPolicies;
    return this;
  }

  /**
   * Output only. Machine name.
   * @return value or {@code null} for none
   */
  public java.lang.String getMachineName() {
    return machineName;
  }

  /**
   * Output only. Machine name.
   * @param machineName machineName or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setMachineName(java.lang.String machineName) {
    this.machineName = machineName;
    return this;
  }

  /**
   * Output only. The list of all device level policies set for Chrome browsers on this device.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1Policy> getMachinePolicies() {
    return machinePolicies;
  }

  /**
   * Output only. The list of all device level policies set for Chrome browsers on this device.
   * @param machinePolicies machinePolicies or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setMachinePolicies(java.util.List<GoogleChromeManagementVersionsV1Policy> machinePolicies) {
    this.machinePolicies = machinePolicies;
    return this;
  }

  /**
   * Identifier. Format: customers/{customer_id}/chromeBrowsers/{browser_permanent_id}
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Identifier. Format: customers/{customer_id}/chromeBrowsers/{browser_permanent_id}
   * @param name name or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Output only. Recent policy fetch activity by Omaha. Not necessarily the last fetch since this
   * field is only updated daily.
   * @return value or {@code null} for none
   */
  public String getOmahaRecentFetchTime() {
    return omahaRecentFetchTime;
  }

  /**
   * Output only. Recent policy fetch activity by Omaha. Not necessarily the last fetch since this
   * field is only updated daily.
   * @param omahaRecentFetchTime omahaRecentFetchTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setOmahaRecentFetchTime(String omahaRecentFetchTime) {
    this.omahaRecentFetchTime = omahaRecentFetchTime;
    return this;
  }

  /**
   * Output only. The obfuscated organizational unit ID of the browser.
   * @return value or {@code null} for none
   */
  public java.lang.String getOrgUnitId() {
    return orgUnitId;
  }

  /**
   * Output only. The obfuscated organizational unit ID of the browser.
   * @param orgUnitId orgUnitId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setOrgUnitId(java.lang.String orgUnitId) {
    this.orgUnitId = orgUnitId;
    return this;
  }

  /**
   * Output only. Device CPU architecture.
   * @return value or {@code null} for none
   */
  public java.lang.String getOsArchitecture() {
    return osArchitecture;
  }

  /**
   * Output only. Device CPU architecture.
   * @param osArchitecture osArchitecture or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setOsArchitecture(java.lang.String osArchitecture) {
    this.osArchitecture = osArchitecture;
    return this;
  }

  /**
   * Output only. Device Os platform.
   * @return value or {@code null} for none
   */
  public java.lang.String getOsPlatform() {
    return osPlatform;
  }

  /**
   * Output only. Device Os platform.
   * @param osPlatform osPlatform or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setOsPlatform(java.lang.String osPlatform) {
    this.osPlatform = osPlatform;
    return this;
  }

  /**
   * Output only. Device Os platform and version combined.
   * @return value or {@code null} for none
   */
  public java.lang.String getOsPlatformVersion() {
    return osPlatformVersion;
  }

  /**
   * Output only. Device Os platform and version combined.
   * @param osPlatformVersion osPlatformVersion or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setOsPlatformVersion(java.lang.String osPlatformVersion) {
    this.osPlatformVersion = osPlatformVersion;
    return this;
  }

  /**
   * Output only. Device Os Version.
   * @return value or {@code null} for none
   */
  public java.lang.String getOsVersion() {
    return osVersion;
  }

  /**
   * Output only. Device Os Version.
   * @param osVersion osVersion or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setOsVersion(java.lang.String osVersion) {
    this.osVersion = osVersion;
    return this;
  }

  /**
   * Output only. The number of distinct policies set on all the Chrome browsers of this device.
   * @return value or {@code null} for none
   */
  public java.lang.Long getPolicyCount() {
    return policyCount;
  }

  /**
   * Output only. The number of distinct policies set on all the Chrome browsers of this device.
   * @param policyCount policyCount or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setPolicyCount(java.lang.Long policyCount) {
    this.policyCount = policyCount;
    return this;
  }

  /**
   * Output only. The device's serial number.
   * @return value or {@code null} for none
   */
  public java.lang.String getSerialNumber() {
    return serialNumber;
  }

  /**
   * Output only. The device's serial number.
   * @param serialNumber serialNumber or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setSerialNumber(java.lang.String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

  /**
   * Output only. The initial device id sent by the first Chrome browser that enrolled this device.
   * @return value or {@code null} for none
   */
  public java.lang.String getVirtualDeviceId() {
    return virtualDeviceId;
  }

  /**
   * Output only. The initial device id sent by the first Chrome browser that enrolled this device.
   * @param virtualDeviceId virtualDeviceId or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1ChromeBrowser setVirtualDeviceId(java.lang.String virtualDeviceId) {
    this.virtualDeviceId = virtualDeviceId;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1ChromeBrowser set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1ChromeBrowser) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1ChromeBrowser clone() {
    return (GoogleChromeManagementVersionsV1ChromeBrowser) super.clone();
  }

}
