/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Record of the device identifiers and when they were reported.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1DeviceIdentifiersRecord extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The first time these identifiers were reported.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String firstRecordTime;

  /**
   * Output only. Device identifiers.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private GoogleChromeManagementVersionsV1DeviceIdentifiers identifiers;

  /**
   * Output only. The time of the last activity of these identifiers either from reporting, policy
   * fetching or registration.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastActivityTime;

  /**
   * Output only. The first time these identifiers were reported.
   * @return value or {@code null} for none
   */
  public String getFirstRecordTime() {
    return firstRecordTime;
  }

  /**
   * Output only. The first time these identifiers were reported.
   * @param firstRecordTime firstRecordTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiersRecord setFirstRecordTime(String firstRecordTime) {
    this.firstRecordTime = firstRecordTime;
    return this;
  }

  /**
   * Output only. Device identifiers.
   * @return value or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiers getIdentifiers() {
    return identifiers;
  }

  /**
   * Output only. Device identifiers.
   * @param identifiers identifiers or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiersRecord setIdentifiers(GoogleChromeManagementVersionsV1DeviceIdentifiers identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  /**
   * Output only. The time of the last activity of these identifiers either from reporting, policy
   * fetching or registration.
   * @return value or {@code null} for none
   */
  public String getLastActivityTime() {
    return lastActivityTime;
  }

  /**
   * Output only. The time of the last activity of these identifiers either from reporting, policy
   * fetching or registration.
   * @param lastActivityTime lastActivityTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiersRecord setLastActivityTime(String lastActivityTime) {
    this.lastActivityTime = lastActivityTime;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1DeviceIdentifiersRecord set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1DeviceIdentifiersRecord) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1DeviceIdentifiersRecord clone() {
    return (GoogleChromeManagementVersionsV1DeviceIdentifiersRecord) super.clone();
  }

}
