/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * History of device identifiers reported from a device.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1DeviceIdentifiersHistory extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The device id is potentially being used by multiple devices.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean deviceIdCollision;

  /**
   * Output only. The last time we detected the device id collision.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private String lastDeviceIdCollisionDetectionTime;

  /**
   * Output only. List of device identifiers sent by this device. In descending order by
   * last_activity_time.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<GoogleChromeManagementVersionsV1DeviceIdentifiersRecord> records;

  /**
   * Output only. The device id is potentially being used by multiple devices.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getDeviceIdCollision() {
    return deviceIdCollision;
  }

  /**
   * Output only. The device id is potentially being used by multiple devices.
   * @param deviceIdCollision deviceIdCollision or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiersHistory setDeviceIdCollision(java.lang.Boolean deviceIdCollision) {
    this.deviceIdCollision = deviceIdCollision;
    return this;
  }

  /**
   * Output only. The last time we detected the device id collision.
   * @return value or {@code null} for none
   */
  public String getLastDeviceIdCollisionDetectionTime() {
    return lastDeviceIdCollisionDetectionTime;
  }

  /**
   * Output only. The last time we detected the device id collision.
   * @param lastDeviceIdCollisionDetectionTime lastDeviceIdCollisionDetectionTime or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiersHistory setLastDeviceIdCollisionDetectionTime(String lastDeviceIdCollisionDetectionTime) {
    this.lastDeviceIdCollisionDetectionTime = lastDeviceIdCollisionDetectionTime;
    return this;
  }

  /**
   * Output only. List of device identifiers sent by this device. In descending order by
   * last_activity_time.
   * @return value or {@code null} for none
   */
  public java.util.List<GoogleChromeManagementVersionsV1DeviceIdentifiersRecord> getRecords() {
    return records;
  }

  /**
   * Output only. List of device identifiers sent by this device. In descending order by
   * last_activity_time.
   * @param records records or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiersHistory setRecords(java.util.List<GoogleChromeManagementVersionsV1DeviceIdentifiersRecord> records) {
    this.records = records;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1DeviceIdentifiersHistory set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1DeviceIdentifiersHistory) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1DeviceIdentifiersHistory clone() {
    return (GoogleChromeManagementVersionsV1DeviceIdentifiersHistory) super.clone();
  }

}
