/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Collection of device identifiers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1DeviceIdentifiers extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The device's host name.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String hostName;

  /**
   * Output only. The name of the machine associated with the device.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String machineName;

  /**
   * Output only. The device's serial number.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String serialNumber;

  /**
   * Output only. The device's host name.
   * @return value or {@code null} for none
   */
  public java.lang.String getHostName() {
    return hostName;
  }

  /**
   * Output only. The device's host name.
   * @param hostName hostName or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiers setHostName(java.lang.String hostName) {
    this.hostName = hostName;
    return this;
  }

  /**
   * Output only. The name of the machine associated with the device.
   * @return value or {@code null} for none
   */
  public java.lang.String getMachineName() {
    return machineName;
  }

  /**
   * Output only. The name of the machine associated with the device.
   * @param machineName machineName or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiers setMachineName(java.lang.String machineName) {
    this.machineName = machineName;
    return this;
  }

  /**
   * Output only. The device's serial number.
   * @return value or {@code null} for none
   */
  public java.lang.String getSerialNumber() {
    return serialNumber;
  }

  /**
   * Output only. The device's serial number.
   * @param serialNumber serialNumber or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1DeviceIdentifiers setSerialNumber(java.lang.String serialNumber) {
    this.serialNumber = serialNumber;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1DeviceIdentifiers set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1DeviceIdentifiers) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1DeviceIdentifiers clone() {
    return (GoogleChromeManagementVersionsV1DeviceIdentifiers) super.clone();
  }

}
