/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * The applied policy reported by a managed Chrome browser. The policy can be applied at various
 * scopes (machine, profile, extension).
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1Policy extends com.google.api.client.json.GenericJson {

  /**
   * Output only. A localized string with all the errors reported when trying to apply this policy,
   * if any.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String error;

  /**
   * Output only. The name of the policy.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String policyName;

  /**
   * Output only. The source of the policy.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String source;

  /**
   * Output only. The value of the policy.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String value;

  /**
   * Output only. A localized string with all the errors reported when trying to apply this policy,
   * if any.
   * @return value or {@code null} for none
   */
  public java.lang.String getError() {
    return error;
  }

  /**
   * Output only. A localized string with all the errors reported when trying to apply this policy,
   * if any.
   * @param error error or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Policy setError(java.lang.String error) {
    this.error = error;
    return this;
  }

  /**
   * Output only. The name of the policy.
   * @return value or {@code null} for none
   */
  public java.lang.String getPolicyName() {
    return policyName;
  }

  /**
   * Output only. The name of the policy.
   * @param policyName policyName or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Policy setPolicyName(java.lang.String policyName) {
    this.policyName = policyName;
    return this;
  }

  /**
   * Output only. The source of the policy.
   * @return value or {@code null} for none
   */
  public java.lang.String getSource() {
    return source;
  }

  /**
   * Output only. The source of the policy.
   * @param source source or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Policy setSource(java.lang.String source) {
    this.source = source;
    return this;
  }

  /**
   * Output only. The value of the policy.
   * @return value or {@code null} for none
   */
  public java.lang.String getValue() {
    return value;
  }

  /**
   * Output only. The value of the policy.
   * @param value value or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Policy setValue(java.lang.String value) {
    this.value = value;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1Policy set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1Policy) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1Policy clone() {
    return (GoogleChromeManagementVersionsV1Policy) super.clone();
  }

}
