/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.chromemanagement.v1.model;

/**
 * Information about a Chrome browser plugin installed on a reported Chrome installation on a device
 * with managed Chrome browsers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Chrome Management API. For a detailed explanation
 * see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class GoogleChromeManagementVersionsV1Plugin extends com.google.api.client.json.GenericJson {

  /**
   * Output only. The description of the installed plugin.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * Output only. The filename of the installed plugin.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String filename;

  /**
   * Output only. The name of the installed plugin.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String pluginName;

  /**
   * Output only. The description of the installed plugin.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Output only. The description of the installed plugin.
   * @param description description or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Plugin setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * Output only. The filename of the installed plugin.
   * @return value or {@code null} for none
   */
  public java.lang.String getFilename() {
    return filename;
  }

  /**
   * Output only. The filename of the installed plugin.
   * @param filename filename or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Plugin setFilename(java.lang.String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * Output only. The name of the installed plugin.
   * @return value or {@code null} for none
   */
  public java.lang.String getPluginName() {
    return pluginName;
  }

  /**
   * Output only. The name of the installed plugin.
   * @param pluginName pluginName or {@code null} for none
   */
  public GoogleChromeManagementVersionsV1Plugin setPluginName(java.lang.String pluginName) {
    this.pluginName = pluginName;
    return this;
  }

  @Override
  public GoogleChromeManagementVersionsV1Plugin set(String fieldName, Object value) {
    return (GoogleChromeManagementVersionsV1Plugin) super.set(fieldName, value);
  }

  @Override
  public GoogleChromeManagementVersionsV1Plugin clone() {
    return (GoogleChromeManagementVersionsV1Plugin) super.clone();
  }

}
