/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.compute.model;

/**
 * Represents the current status of the AliasNetworkEndpoint.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Compute Engine API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AliasNetworkEndpointStatus extends com.google.api.client.json.GenericJson {

  /**
   * Output only. [Output Only] The URL of the network that this alias network endpoint belongs to.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String network;

  /**
   * Output only. [Output Only] The state of the alias network endpoint.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String state;

  /**
   * Output only. [Output Only] The URL of the network that this alias network endpoint belongs to.
   * @return value or {@code null} for none
   */
  public java.lang.String getNetwork() {
    return network;
  }

  /**
   * Output only. [Output Only] The URL of the network that this alias network endpoint belongs to.
   * @param network network or {@code null} for none
   */
  public AliasNetworkEndpointStatus setNetwork(java.lang.String network) {
    this.network = network;
    return this;
  }

  /**
   * Output only. [Output Only] The state of the alias network endpoint.
   * @return value or {@code null} for none
   */
  public java.lang.String getState() {
    return state;
  }

  /**
   * Output only. [Output Only] The state of the alias network endpoint.
   * @param state state or {@code null} for none
   */
  public AliasNetworkEndpointStatus setState(java.lang.String state) {
    this.state = state;
    return this;
  }

  @Override
  public AliasNetworkEndpointStatus set(String fieldName, Object value) {
    return (AliasNetworkEndpointStatus) super.set(fieldName, value);
  }

  @Override
  public AliasNetworkEndpointStatus clone() {
    return (AliasNetworkEndpointStatus) super.clone();
  }

}
