/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.compute.model;

/**
 * Represents an Alias Network Endpoint resource. To be used for GKE pod-native endpoints in
 * Andromeda.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Compute Engine API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AliasNetworkEndpoint extends com.google.api.client.json.GenericJson {

  /**
   * Required. The map of network aliases allocated for the AliasNetworkEndpoint. This map is keyed
   * with user-provided alias names.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, AliasNetworkEndpointAlias> aliases;

  /**
   * Optional. The annotations map for the AliasNetworkEndpoint. Keys and values must follow
   * Kubernetes limits. Keys must be a maximum of 253 characters. Keys should be dot-namespaced,
   * following the Kubernetes annotation key format: `([DNS subdomain]/)?[RFC 1123 name]`. Values
   * must be a maximum of 256 characters.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.lang.String> annotations;

  /**
   * Output only. [Output Only] Creation timestamp in RFC3339 text format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String creationTimestamp;

  /**
   * Optional. An optional description of this resource. Provide this field when you create the
   * resource.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * Required. The host that the alias network endpoint is bound to.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AliasNetworkEndpointHost host;

  /**
   * Output only. [Output Only] The unique identifier for the resource. This identifier is defined
   * by the server.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.math.BigInteger id;

  /**
   * Optional. The labels map for the AliasNetworkEndpoint.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, java.lang.String> labels;

  /**
   * Identifier. Name of the resource. Provided by the client when the resource is created. The name
   * must be 1-63 characters long, and comply with RFC1035.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * Optional. The security tag inheritance setting for the AliasNetworkEndpoint.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String securityTagInheritance;

  /**
   * Output only. [Output Only] Server-defined URL for the resource.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String selfLink;

  /**
   * Output only. [Output Only] Current status of the alias network endpoint.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private AliasNetworkEndpointStatus status;

  /**
   * Required. The URL of the subnetwork that this alias network endpoint belongs to.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String subnetwork;

  /**
   * Output only. [Output Only] Update timestamp in RFC3339 text format.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String updateTime;

  /**
   * Required. The map of network aliases allocated for the AliasNetworkEndpoint. This map is keyed
   * with user-provided alias names.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, AliasNetworkEndpointAlias> getAliases() {
    return aliases;
  }

  /**
   * Required. The map of network aliases allocated for the AliasNetworkEndpoint. This map is keyed
   * with user-provided alias names.
   * @param aliases aliases or {@code null} for none
   */
  public AliasNetworkEndpoint setAliases(java.util.Map<String, AliasNetworkEndpointAlias> aliases) {
    this.aliases = aliases;
    return this;
  }

  /**
   * Optional. The annotations map for the AliasNetworkEndpoint. Keys and values must follow
   * Kubernetes limits. Keys must be a maximum of 253 characters. Keys should be dot-namespaced,
   * following the Kubernetes annotation key format: `([DNS subdomain]/)?[RFC 1123 name]`. Values
   * must be a maximum of 256 characters.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.lang.String> getAnnotations() {
    return annotations;
  }

  /**
   * Optional. The annotations map for the AliasNetworkEndpoint. Keys and values must follow
   * Kubernetes limits. Keys must be a maximum of 253 characters. Keys should be dot-namespaced,
   * following the Kubernetes annotation key format: `([DNS subdomain]/)?[RFC 1123 name]`. Values
   * must be a maximum of 256 characters.
   * @param annotations annotations or {@code null} for none
   */
  public AliasNetworkEndpoint setAnnotations(java.util.Map<String, java.lang.String> annotations) {
    this.annotations = annotations;
    return this;
  }

  /**
   * Output only. [Output Only] Creation timestamp in RFC3339 text format.
   * @return value or {@code null} for none
   */
  public java.lang.String getCreationTimestamp() {
    return creationTimestamp;
  }

  /**
   * Output only. [Output Only] Creation timestamp in RFC3339 text format.
   * @param creationTimestamp creationTimestamp or {@code null} for none
   */
  public AliasNetworkEndpoint setCreationTimestamp(java.lang.String creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
    return this;
  }

  /**
   * Optional. An optional description of this resource. Provide this field when you create the
   * resource.
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * Optional. An optional description of this resource. Provide this field when you create the
   * resource.
   * @param description description or {@code null} for none
   */
  public AliasNetworkEndpoint setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * Required. The host that the alias network endpoint is bound to.
   * @return value or {@code null} for none
   */
  public AliasNetworkEndpointHost getHost() {
    return host;
  }

  /**
   * Required. The host that the alias network endpoint is bound to.
   * @param host host or {@code null} for none
   */
  public AliasNetworkEndpoint setHost(AliasNetworkEndpointHost host) {
    this.host = host;
    return this;
  }

  /**
   * Output only. [Output Only] The unique identifier for the resource. This identifier is defined
   * by the server.
   * @return value or {@code null} for none
   */
  public java.math.BigInteger getId() {
    return id;
  }

  /**
   * Output only. [Output Only] The unique identifier for the resource. This identifier is defined
   * by the server.
   * @param id id or {@code null} for none
   */
  public AliasNetworkEndpoint setId(java.math.BigInteger id) {
    this.id = id;
    return this;
  }

  /**
   * Optional. The labels map for the AliasNetworkEndpoint.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, java.lang.String> getLabels() {
    return labels;
  }

  /**
   * Optional. The labels map for the AliasNetworkEndpoint.
   * @param labels labels or {@code null} for none
   */
  public AliasNetworkEndpoint setLabels(java.util.Map<String, java.lang.String> labels) {
    this.labels = labels;
    return this;
  }

  /**
   * Identifier. Name of the resource. Provided by the client when the resource is created. The name
   * must be 1-63 characters long, and comply with RFC1035.
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * Identifier. Name of the resource. Provided by the client when the resource is created. The name
   * must be 1-63 characters long, and comply with RFC1035.
   * @param name name or {@code null} for none
   */
  public AliasNetworkEndpoint setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * Optional. The security tag inheritance setting for the AliasNetworkEndpoint.
   * @return value or {@code null} for none
   */
  public java.lang.String getSecurityTagInheritance() {
    return securityTagInheritance;
  }

  /**
   * Optional. The security tag inheritance setting for the AliasNetworkEndpoint.
   * @param securityTagInheritance securityTagInheritance or {@code null} for none
   */
  public AliasNetworkEndpoint setSecurityTagInheritance(java.lang.String securityTagInheritance) {
    this.securityTagInheritance = securityTagInheritance;
    return this;
  }

  /**
   * Output only. [Output Only] Server-defined URL for the resource.
   * @return value or {@code null} for none
   */
  public java.lang.String getSelfLink() {
    return selfLink;
  }

  /**
   * Output only. [Output Only] Server-defined URL for the resource.
   * @param selfLink selfLink or {@code null} for none
   */
  public AliasNetworkEndpoint setSelfLink(java.lang.String selfLink) {
    this.selfLink = selfLink;
    return this;
  }

  /**
   * Output only. [Output Only] Current status of the alias network endpoint.
   * @return value or {@code null} for none
   */
  public AliasNetworkEndpointStatus getStatus() {
    return status;
  }

  /**
   * Output only. [Output Only] Current status of the alias network endpoint.
   * @param status status or {@code null} for none
   */
  public AliasNetworkEndpoint setStatus(AliasNetworkEndpointStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Required. The URL of the subnetwork that this alias network endpoint belongs to.
   * @return value or {@code null} for none
   */
  public java.lang.String getSubnetwork() {
    return subnetwork;
  }

  /**
   * Required. The URL of the subnetwork that this alias network endpoint belongs to.
   * @param subnetwork subnetwork or {@code null} for none
   */
  public AliasNetworkEndpoint setSubnetwork(java.lang.String subnetwork) {
    this.subnetwork = subnetwork;
    return this;
  }

  /**
   * Output only. [Output Only] Update timestamp in RFC3339 text format.
   * @return value or {@code null} for none
   */
  public java.lang.String getUpdateTime() {
    return updateTime;
  }

  /**
   * Output only. [Output Only] Update timestamp in RFC3339 text format.
   * @param updateTime updateTime or {@code null} for none
   */
  public AliasNetworkEndpoint setUpdateTime(java.lang.String updateTime) {
    this.updateTime = updateTime;
    return this;
  }

  @Override
  public AliasNetworkEndpoint set(String fieldName, Object value) {
    return (AliasNetworkEndpoint) super.set(fieldName, value);
  }

  @Override
  public AliasNetworkEndpoint clone() {
    return (AliasNetworkEndpoint) super.clone();
  }

}
