/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.compute.model;

/**
 * Configuration for an IP alias.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Compute Engine API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class AliasNetworkEndpointAlias extends com.google.api.client.json.GenericJson {

  /**
   * Output only. [Output Only] The actual IP address allocated by the system.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String effectiveIpAddress;

  /**
   * Output only. [Output Only] The actual secondary range used for allocation.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String effectiveSubnetworkRangeName;

  /**
   * Input only. The IP address of the network endpoint. If specified, the server performs a
   * validation check for uniqueness. If the field is omitted, the system automatically allocates an
   * IP and populates the effective_ip_address field.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ipAddress;

  /**
   * Required. The IP version of the IP. It is IPv4 or IPv6.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ipVersion;

  /**
   * Input only. Defines candidate secondary ranges for allocating the alias IPs. If it is empty,
   * the IP would be allocated from the primary range of the subnetwork. This field is INPUT_ONLY
   * and used only during resource creation, hence a repeated field is acceptable as per AIP-2825.
   * It is not mutable.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<java.lang.String> subnetworkRangeNames;

  /**
   * Output only. [Output Only] The actual IP address allocated by the system.
   * @return value or {@code null} for none
   */
  public java.lang.String getEffectiveIpAddress() {
    return effectiveIpAddress;
  }

  /**
   * Output only. [Output Only] The actual IP address allocated by the system.
   * @param effectiveIpAddress effectiveIpAddress or {@code null} for none
   */
  public AliasNetworkEndpointAlias setEffectiveIpAddress(java.lang.String effectiveIpAddress) {
    this.effectiveIpAddress = effectiveIpAddress;
    return this;
  }

  /**
   * Output only. [Output Only] The actual secondary range used for allocation.
   * @return value or {@code null} for none
   */
  public java.lang.String getEffectiveSubnetworkRangeName() {
    return effectiveSubnetworkRangeName;
  }

  /**
   * Output only. [Output Only] The actual secondary range used for allocation.
   * @param effectiveSubnetworkRangeName effectiveSubnetworkRangeName or {@code null} for none
   */
  public AliasNetworkEndpointAlias setEffectiveSubnetworkRangeName(java.lang.String effectiveSubnetworkRangeName) {
    this.effectiveSubnetworkRangeName = effectiveSubnetworkRangeName;
    return this;
  }

  /**
   * Input only. The IP address of the network endpoint. If specified, the server performs a
   * validation check for uniqueness. If the field is omitted, the system automatically allocates an
   * IP and populates the effective_ip_address field.
   * @return value or {@code null} for none
   */
  public java.lang.String getIpAddress() {
    return ipAddress;
  }

  /**
   * Input only. The IP address of the network endpoint. If specified, the server performs a
   * validation check for uniqueness. If the field is omitted, the system automatically allocates an
   * IP and populates the effective_ip_address field.
   * @param ipAddress ipAddress or {@code null} for none
   */
  public AliasNetworkEndpointAlias setIpAddress(java.lang.String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  /**
   * Required. The IP version of the IP. It is IPv4 or IPv6.
   * @return value or {@code null} for none
   */
  public java.lang.String getIpVersion() {
    return ipVersion;
  }

  /**
   * Required. The IP version of the IP. It is IPv4 or IPv6.
   * @param ipVersion ipVersion or {@code null} for none
   */
  public AliasNetworkEndpointAlias setIpVersion(java.lang.String ipVersion) {
    this.ipVersion = ipVersion;
    return this;
  }

  /**
   * Input only. Defines candidate secondary ranges for allocating the alias IPs. If it is empty,
   * the IP would be allocated from the primary range of the subnetwork. This field is INPUT_ONLY
   * and used only during resource creation, hence a repeated field is acceptable as per AIP-2825.
   * It is not mutable.
   * @return value or {@code null} for none
   */
  public java.util.List<java.lang.String> getSubnetworkRangeNames() {
    return subnetworkRangeNames;
  }

  /**
   * Input only. Defines candidate secondary ranges for allocating the alias IPs. If it is empty,
   * the IP would be allocated from the primary range of the subnetwork. This field is INPUT_ONLY
   * and used only during resource creation, hence a repeated field is acceptable as per AIP-2825.
   * It is not mutable.
   * @param subnetworkRangeNames subnetworkRangeNames or {@code null} for none
   */
  public AliasNetworkEndpointAlias setSubnetworkRangeNames(java.util.List<java.lang.String> subnetworkRangeNames) {
    this.subnetworkRangeNames = subnetworkRangeNames;
    return this;
  }

  @Override
  public AliasNetworkEndpointAlias set(String fieldName, Object value) {
    return (AliasNetworkEndpointAlias) super.set(fieldName, value);
  }

  @Override
  public AliasNetworkEndpointAlias clone() {
    return (AliasNetworkEndpointAlias) super.clone();
  }

}
