/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.compute.model;

/**
 * Additional HA Controller params.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Compute Engine API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HaControllerParams extends com.google.api.client.json.GenericJson {

  /**
   * Specifies whether to automatically migrate all disks of an instance from zonal to regional
   * before attempting to create the HaController.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean migrateDisksToRegional;

  /**
   * Specifies whether to automatically migrate all disks of an instance from zonal to regional
   * before attempting to create the HaController.
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getMigrateDisksToRegional() {
    return migrateDisksToRegional;
  }

  /**
   * Specifies whether to automatically migrate all disks of an instance from zonal to regional
   * before attempting to create the HaController.
   * @param migrateDisksToRegional migrateDisksToRegional or {@code null} for none
   */
  public HaControllerParams setMigrateDisksToRegional(java.lang.Boolean migrateDisksToRegional) {
    this.migrateDisksToRegional = migrateDisksToRegional;
    return this;
  }

  @Override
  public HaControllerParams set(String fieldName, Object value) {
    return (HaControllerParams) super.set(fieldName, value);
  }

  @Override
  public HaControllerParams clone() {
    return (HaControllerParams) super.clone();
  }

}
