/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.compute.model;

/**
 * The network interface configuration of the VM instance.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Compute Engine API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HaControllerInstanceNetworkInterface extends com.google.api.client.json.GenericJson {

  /**
   * Optional. Optional IPv6 address to assign to the instance's network interface. If omitted, an
   * ephemeral IP may be assigned depending on the instance's network interface stack type.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String ipv6Address;

  /**
   * Optional. Optional IPv4 address to assign to the instance's network interface. If omitted, an
   * ephemeral IP may be assigned depending on the instance's network interface stack type.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String networkIP;

  /**
   * Optional. Optional IPv6 address to assign to the instance's network interface. If omitted, an
   * ephemeral IP may be assigned depending on the instance's network interface stack type.
   * @return value or {@code null} for none
   */
  public java.lang.String getIpv6Address() {
    return ipv6Address;
  }

  /**
   * Optional. Optional IPv6 address to assign to the instance's network interface. If omitted, an
   * ephemeral IP may be assigned depending on the instance's network interface stack type.
   * @param ipv6Address ipv6Address or {@code null} for none
   */
  public HaControllerInstanceNetworkInterface setIpv6Address(java.lang.String ipv6Address) {
    this.ipv6Address = ipv6Address;
    return this;
  }

  /**
   * Optional. Optional IPv4 address to assign to the instance's network interface. If omitted, an
   * ephemeral IP may be assigned depending on the instance's network interface stack type.
   * @return value or {@code null} for none
   */
  public java.lang.String getNetworkIP() {
    return networkIP;
  }

  /**
   * Optional. Optional IPv4 address to assign to the instance's network interface. If omitted, an
   * ephemeral IP may be assigned depending on the instance's network interface stack type.
   * @param networkIP networkIP or {@code null} for none
   */
  public HaControllerInstanceNetworkInterface setNetworkIP(java.lang.String networkIP) {
    this.networkIP = networkIP;
    return this;
  }

  @Override
  public HaControllerInstanceNetworkInterface set(String fieldName, Object value) {
    return (HaControllerInstanceNetworkInterface) super.set(fieldName, value);
  }

  @Override
  public HaControllerInstanceNetworkInterface clone() {
    return (HaControllerInstanceNetworkInterface) super.clone();
  }

}
