/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://github.com/googleapis/google-api-java-client-services/
 * Modify at your own risk.
 */

package com.google.api.services.compute.model;

/**
 * Config for a zone that the HaController may use for running the VM instance.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the Compute Engine API. For a detailed explanation see:
 * <a href="https://developers.google.com/api-client-library/java/google-http-java-client/json">https://developers.google.com/api-client-library/java/google-http-java-client/json</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class HaControllerZoneConfiguration extends com.google.api.client.json.GenericJson {

  /**
   * Optional. The network interface configuration of a VM instance in this zone, keyed by the name
   * of the network interface. A VM network interface uses the nicN naming format, where N is a
   * value between 0 and 7. The default interface is nic0. Use this field to choose the internal IP
   * addresses of the VM instance in this zone instead of letting Compute Engine assign them
   * automatically.               - Each key must be a name of a network interface that exists on
   * the VM instance. Otherwise, the request fails.       - Network interfaces that are omitted are
   * assigned an ephemeral       internal IP address.       - Every zone must configure the same
   * network interfaces and the       same IP address families.       - For the zone that currently
   * holds the VM instance, this field       is populated automatically, and any addresses you
   * specify must       match the instance's current addresses.       - Only internal IP addresses
   * are supported, and this field can       only be set when the HA Controller is created.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.Map<String, HaControllerInstanceNetworkInterface> instanceNetworkInterfaces;

  static {
    // hack to force ProGuard to consider HaControllerInstanceNetworkInterface used, since otherwise it would be stripped out
    // see https://github.com/google/google-api-java-client/issues/543
    com.google.api.client.util.Data.nullOf(HaControllerInstanceNetworkInterface.class);
  }

  /**
   * A set of node affinity configurations. Refer toConfiguring node affinity for more information.
   * Overrides reservationAffinity.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.util.List<HaControllerZoneConfigurationNodeAffinity> nodeAffinities;

  /**
   * Specifies the reservations that the instance can consume from.
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private HaControllerZoneConfigurationReservationAffinity reservationAffinity;

  /**
   * Optional. The network interface configuration of a VM instance in this zone, keyed by the name
   * of the network interface. A VM network interface uses the nicN naming format, where N is a
   * value between 0 and 7. The default interface is nic0. Use this field to choose the internal IP
   * addresses of the VM instance in this zone instead of letting Compute Engine assign them
   * automatically.               - Each key must be a name of a network interface that exists on
   * the VM instance. Otherwise, the request fails.       - Network interfaces that are omitted are
   * assigned an ephemeral       internal IP address.       - Every zone must configure the same
   * network interfaces and the       same IP address families.       - For the zone that currently
   * holds the VM instance, this field       is populated automatically, and any addresses you
   * specify must       match the instance's current addresses.       - Only internal IP addresses
   * are supported, and this field can       only be set when the HA Controller is created.
   * @return value or {@code null} for none
   */
  public java.util.Map<String, HaControllerInstanceNetworkInterface> getInstanceNetworkInterfaces() {
    return instanceNetworkInterfaces;
  }

  /**
   * Optional. The network interface configuration of a VM instance in this zone, keyed by the name
   * of the network interface. A VM network interface uses the nicN naming format, where N is a
   * value between 0 and 7. The default interface is nic0. Use this field to choose the internal IP
   * addresses of the VM instance in this zone instead of letting Compute Engine assign them
   * automatically.               - Each key must be a name of a network interface that exists on
   * the VM instance. Otherwise, the request fails.       - Network interfaces that are omitted are
   * assigned an ephemeral       internal IP address.       - Every zone must configure the same
   * network interfaces and the       same IP address families.       - For the zone that currently
   * holds the VM instance, this field       is populated automatically, and any addresses you
   * specify must       match the instance's current addresses.       - Only internal IP addresses
   * are supported, and this field can       only be set when the HA Controller is created.
   * @param instanceNetworkInterfaces instanceNetworkInterfaces or {@code null} for none
   */
  public HaControllerZoneConfiguration setInstanceNetworkInterfaces(java.util.Map<String, HaControllerInstanceNetworkInterface> instanceNetworkInterfaces) {
    this.instanceNetworkInterfaces = instanceNetworkInterfaces;
    return this;
  }

  /**
   * A set of node affinity configurations. Refer toConfiguring node affinity for more information.
   * Overrides reservationAffinity.
   * @return value or {@code null} for none
   */
  public java.util.List<HaControllerZoneConfigurationNodeAffinity> getNodeAffinities() {
    return nodeAffinities;
  }

  /**
   * A set of node affinity configurations. Refer toConfiguring node affinity for more information.
   * Overrides reservationAffinity.
   * @param nodeAffinities nodeAffinities or {@code null} for none
   */
  public HaControllerZoneConfiguration setNodeAffinities(java.util.List<HaControllerZoneConfigurationNodeAffinity> nodeAffinities) {
    this.nodeAffinities = nodeAffinities;
    return this;
  }

  /**
   * Specifies the reservations that the instance can consume from.
   * @return value or {@code null} for none
   */
  public HaControllerZoneConfigurationReservationAffinity getReservationAffinity() {
    return reservationAffinity;
  }

  /**
   * Specifies the reservations that the instance can consume from.
   * @param reservationAffinity reservationAffinity or {@code null} for none
   */
  public HaControllerZoneConfiguration setReservationAffinity(HaControllerZoneConfigurationReservationAffinity reservationAffinity) {
    this.reservationAffinity = reservationAffinity;
    return this;
  }

  @Override
  public HaControllerZoneConfiguration set(String fieldName, Object value) {
    return (HaControllerZoneConfiguration) super.set(fieldName, value);
  }

  @Override
  public HaControllerZoneConfiguration clone() {
    return (HaControllerZoneConfiguration) super.clone();
  }

}
